### PR TITLE
Create cpp.md

### PR DESCRIPTION
**Pull request by frag-o-matic**

### CODE REVIEW

**Comment by avinassh** [comment]
Hey thanks for the PR. The curriculum looks great and exhaustive. However you also need to add courses, they could be other online MooCs, Youtube playlists and also a book, beginner could follow. Why is that? If you include all those resources mentee can start on his own. Or else you have to constantly provide resources to him for every `xyz` topic. Makes sense?

**Comment by frag-o-matic** [comment]
Agreed, but for cpp I couldn't find any good moocs, there is one for c devs wanting to learn CPP, but nothing from scratch. I guess I could include links to some good books and a whatever else I can find.

The idea was that the mentee could follow along those topics (yet to flesh out the details) and learn modern CPP from get go rather than learn c first n hen transition into cpp

**Comment by avinassh** [comment]
Well you have to spend lot of time, otherwise. At least add a beginner level book.

**Comment by frag-o-matic** [comment]
Yup will add books, there are several good ones that teach modern CPP from the beginning. Should help get ppl started as I'm working on rest of the content

**Comment by avinassh** [comment]
Yes, please do.

**Comment by avinassh** [comment]
You can also add about the https://github.com/frag-o-matic/cpptutorial in the curriculum and mention it as `experimental`. See this for example: https://github.com/code-together/mentorship/blob/master/curriculum/software-development.md

**Comment by frag-o-matic** [comment]
Updated the course curriculum and marked it as experimental. The file is now `experimental_cpp.md`
Added Books and References relevant for modern C++

**Pull request closed without merging**
