### PR TITLE
PR for Modern C++ Tutorial

### PR DESCRIPTION
**Pull request by frag-o-matic**
Changes for adding the Modern C++ tutorial to mentorship repo

### CODE REVIEW

**Comment by frag-o-matic** [comment]
Changes over past few days consolidated and rebased to lastest. I've closed the older PRs.

**Comment by avinassh** [comment]
Looks good to merge! 

Can you squash the commits?

**Comment by frag-o-matic** [comment]
Done

**Comment by avinassh** [comment]
Hey I still see that commits, can you squash them? (I guess you have rebased them, but you also need to squash)

http://stackoverflow.com/a/5190323/1382297

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by frag-o-matic** [comment]
Please try a merge now, the commits are squashed

**Pull request closed without merging**
