### PR TITLE
Added myself

### PR DESCRIPTION
**Pull request by sahaRatul**

### CODE REVIEW

**Comment by avinassh** [comment]
Hey thanks for the PR. Can you also add curriculum for `C` and `MATLAB`?  (`Java` will be done by @anirudhvarma12)

**Comment by sahaRatul** [comment]
C/Matlab/C debugging/Linux

**Comment by sahaRatul** [comment]
Only basics of linux I mean

**Comment by avinassh** [comment]
Sure not an issue. Please see what should an curriculum can include: https://github.com/code-together/mentorship/tree/master/curriculum

**Pull request closed without merging**
